### ISSUE TITLE
[Bug] Incorrect Age Ratings for some titles

### ISSUE THREAD

**Issue by Nomelas** [rommapp/romm#1743]
**RomM version**
3.8.2.alpha.2

**Describe the bug**
Some age ratings for IGDB are displaying an incorrect icon.

**To Reproduce**

1. Go to Dragon Warrior III for GBC
2. Refresh Metadata to pull in Age Ratings
3. Observe that these are the 2 ratings (taken from the api):
```
    "age_ratings": [
      {
        "rating": "Eighteen",
        "category": "PEGI",
        "rating_cover_url": "https://www.igdb.com/icons/rating_icons/pegi/pegi_18.png"
      },
      {
        "rating": "CERO_A",
        "category": "CERO",
        "rating_cover_url": "https://www.igdb.com/icons/rating_icons/cero/cero_a.png"
      }
    ],
```

**Expected behavior**
As per the actual entry in IGDB found here: https://www.igdb.com/games/dragon-warrior-iii--1
`Teen` is the `ESRB` for this title, and not `Eighteen` from `PEGI`. The other rating is correct.

**Screenshots**
![Image](https://github.com/user-attachments/assets/4c643c4e-6787-4d91-b1c5-725c269a81c1)
vs
![Image](https://github.com/user-attachments/assets/d01951c8-6ce4-4cd3-a3e9-b8a2c7a07373)

**Additional context**
I have seen lots of other examples, for instance Kirby's Dream Land for GB shows PEGI 3 twice, instead of E for one of them and similar for Kirby 2 showing PEGI 3 and PEGI 12 (which should be E). ESRB seems like the common issue here.

**Comment by gantoine** [comment]
This should be fixed in the latest release (3.10.1), bug please reply if that's not the case after a complete rescan.

**Comment by HynesJeff57** [comment]
It seems to still show 18+ for DW3 on gbc even after a complete rescan. I also tried unmatching and re-matching to IGDB

**Comment by gantoine** [comment]
Ok I've fixed this on master, and it'll be in the next release! Turns out some of the IDs were wrong and pointing to the wrong images.

<img width="783" alt="Image" src="https://github.com/user-attachments/assets/273a7caf-516c-4ae4-82f6-4319e0195a44" />
