### ISSUE TITLE
[Bug] Games with no rating do not show up in platform

### ISSUE THREAD

**Issue by danieltr3s** [rommapp/romm#2791]
**RomM version**
4.4.1

**Describe the bug**
Games that have no rating, either from being unmatched or matched but with no community rating, e.g.: 3-D Ultra Pinball: Creep Night from Sierra on IGDB, do not show up on the respective platform view.

As consequence, another bug is introduced: This means that the "Show Unmatched" filter also doesn't work as it does not show any games in any platform when active.

**Comment by gantoine** [comment]
Can't seem to reproduce this, here is 3-D Ultra Pinball with no metadata sources at all (unmatched) showing up on the platform list. Maybe this was fixed on the road to 4.5.0, can you try the beta?

<img width="353" height="304" alt="Image" src="https://github.com/user-attachments/assets/4643cb67-e4cd-48cc-bf7f-f9b55b66101e" />
<img width="883" height="458" alt="Image" src="https://github.com/user-attachments/assets/b1576f58-25b5-46f7-9816-6ebb46d6cc8c" />

**Comment by SisterVersio** [comment]
I'm getting this issue as well on both latest and 4.5.0-beta2, when a game is unmatched. Manually adding an IGDB ID for a different game makes it appear

It is possible this issue only happens when renaming the file as well.

**Comment by danieltr3s** [comment]
Hi @gantoine thank you for your effort and reply.
I've tried with both beta.1 and beta.3 and the issue persists. However I believe I've found the bug.
I had a look at the requests and the issue happens when the results are ordered by "average_rating" (order_by=average_rating). Once I removed the argument from the request, all entries were returned.

I hope this information helps fixing the bug!

Best regards,
Daniel

**Comment by SisterVersio** [comment]
This issue is not resolved for me in the release of 4.5.0 although the PR was listed in the changelog, still have to attribute a random IGDB ID

**Comment by zurdi15** [comment]
> This issue is not resolved for me in the release of 4.5.0 although the PR was listed in the changelog, still have to attribute a random IGDB ID

I just tested in my own instance and I can't reproduce the issue. I added the ``3-D Ultra Pinball: Creep Night.exe`` file to ``win`` and after a quick scan it shows in the gallery as unmatched without any kind of metadata.

No filters applied in gallery. When applying unmatched filter it shows the ``3-D Ultra Pinball: Creep Night.exe`` only as expected.

No renaming, nothing special. Just added the file to the library and performed a quick scan

EDIT: while i'm maintaining that it works from the RomM frontend since we don't make any ``order_by`` in the gallery besides name, true is that the API will respond with inconsistent results when ordering by a field that can be null

**Comment by zurdi15** [comment]
A whole rework of filters will happen in #2411 that should make the filtering way more robust
